const tg=window.Telegram?.WebApp;const state={initData:tg?.initData||"",user:null,settings:null,services:[],service:null,date:null,start:null};const $=id=>document.getElementById(id);
function msg(s){const e=$("toast");e.textContent=s;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2500)}
async function api(action,data={}){const r=await fetch("/.netlify/functions/booking",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,initData:state.initData,...data})});const j=await r.json();if(!j.ok)throw Error(j.error||"Помилка");return j}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#039;"}[c]))}
function apply(s){for(const[k,v]of Object.entries(s.colors||{}))document.documentElement.style.setProperty(`--${k}`,v);$("salonName").textContent=s.salonName||"Booking";if(s.logoUrl){$("logo").src=s.logoUrl;$("logo").hidden=false}}
function iso(d){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)}
function mins(t){const[a,b]=t.split(":").map(Number);return a*60+b}
function time(m){return String(Math.floor(m/60)).padStart(2,"0")+":"+String(m%60).padStart(2,"0")}
async function init(){tg?.ready();tg?.expand();if(!state.initData){msg("Відкрийте Mini App через Telegram");return}try{const j=await api("bootstrap");state.user=j.user;state.settings=j.settings;state.services=j.services;apply(j.settings);renderServices();if(j.user.isMaster){$("clientView").classList.add("hidden");$("adminView").classList.remove("hidden");$("adminDate").value=iso(new Date());renderManual();await adminCalendar()}}catch(e){msg(e.message)}}
function renderServices(){const box=$("services");box.innerHTML="";state.services.forEach(s=>{const b=document.createElement("button");b.className="service";b.innerHTML=`<div class="service-top"><span>${esc(s.name)}</span><span>${s.price} грн</span></div><div class="meta"><span>${s.duration} хв</span><span>${s.type==="complex"?"Комплекс":"Послуга"}</span></div>`;b.onclick=()=>{document.querySelectorAll(".service").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.service=s;state.date=null;state.start=null;$("dateCard").classList.remove("hidden");$("slotCard").classList.add("hidden");$("formCard").classList.add("hidden");renderDates()};box.appendChild(b)})}
function renderDates(){const box=$("dates");box.innerHTML="";for(let i=0;i<21;i++){const d=new Date();d.setDate(d.getDate()+i);const id=iso(d);const b=document.createElement("button");b.className="date";if(id===state.date)b.classList.add("selected");b.innerHTML=`${d.getDate()}<small>${d.toLocaleDateString("uk-UA",{month:"short"})}</small>`;b.onclick=async()=>{state.date=id;document.querySelectorAll(".date").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");await slots()};box.appendChild(b)}}
async function slots(){try{const j=await api("getSlots",{date:state.date,serviceId:state.service.id});const box=$("slots");box.innerHTML=j.slots.length?j.slots.map(x=>`<button class="slot" data-time="${x}">${x}</button>`).join(""):"<div class='note'>На цю дату немає доступних віконець.</div>";document.querySelectorAll(".slot").forEach(b=>b.onclick=()=>{document.querySelectorAll(".slot").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.start=b.dataset.time;$("formCard").classList.remove("hidden")});$("slotCard").classList.remove("hidden")}catch(e){msg(e.message)}}
$("book").onclick=async()=>{try{const j=await api("createBooking",{date:state.date,start:state.start,serviceId:state.service.id,clientName:$("name").value,phone:$("phone").value,comment:$("comment").value});$("result").classList.remove("hidden");$("result").innerHTML=`<span class="label">ГОТОВО</span><h2>Запис підтверджено 🧡</h2><p>${esc(j.booking.serviceName)}</p><p>📅 ${j.booking.date} · 🕐 ${j.booking.start}</p>`}catch(e){msg(e.message)}};
$("mine").onclick=async()=>{try{const j=await api("myBookings");$("result").classList.remove("hidden");$("result").innerHTML=`<span class="label">МОЇ ЗАПИСИ</span><h2>${j.bookings.length?"":"Записів немає"}</h2>`+j.bookings.map(b=>`<div class="card"><b>${esc(b.serviceName)}</b><br>${b.date} · ${b.start}<br><button class="secondary" onclick="cancel('${b.id}')">Скасувати</button></div>`).join("")}catch(e){msg(e.message)}};window.cancel=async id=>{try{await api("cancelBooking",{bookingId:id});msg("Запис скасовано");$("mine").click()}catch(e){msg(e.message)}};
async function adminCalendar(){try{const j=await api("adminCalendar",{date:$("adminDate").value});const events=[...j.bookings.map(b=>({start:b.start,end:b.end,type:state.services.find(s=>s.id===b.serviceId)?.type||"single",title:b.serviceName,sub:b.clientName})),...j.blocks.map(b=>({start:b.start,end:b.end,type:"block",title:"🔒 "+b.reason,sub:"Заблоковано"}))];const box=$("adminCalendar");box.innerHTML='<div class="note">Календар показує записи з Bookings і блокування з Blocks. Прайс, тривалості та графік беруться з таблиць.</div>';for(let m=0;m<1440;m+=30){const row=document.createElement("div");row.className="time-row";const label=document.createElement("div");label.className="time";label.textContent=time(m);const cell=document.createElement("div");cell.className="cell";events.filter(e=>m>=mins(e.start)&&m<mins(e.end)).forEach(e=>{const v=document.createElement("div");v.className="event "+e.type;v.innerHTML=esc(e.title)+`<small>${esc(e.sub)}</small>`;cell.appendChild(v)});row.append(label,cell);box.appendChild(row)}}catch(e){msg(e.message)}}
function renderManual(){$("manualService").innerHTML=state.services.map(s=>`<option value="${s.id}">${esc(s.name)} — ${s.duration} хв</option>`).join("")}$("adminDate").onchange=adminCalendar;$("refresh").onclick=adminCalendar;$("block").onclick=async()=>{try{await api("adminAddBlock",{date:$("adminDate").value,start:$("blockStart").value,end:$("blockEnd").value,reason:$("blockReason").value});msg("Час заблоковано");await adminCalendar()}catch(e){msg(e.message)}};$("manual").onclick=async()=>{try{await api("adminManualBooking",{date:$("adminDate").value,start:$("manualStart").value,serviceId:$("manualService").value,clientName:$("manualName").value,phone:$("manualPhone").value});msg("Запис додано");await adminCalendar()}catch(e){msg(e.message)}};init();
