const N={SETTINGS:'Settings',SERVICES:'Services',SCHEDULE:'Schedule',BLOCKS:'Blocks',BOOKINGS:'Bookings',CLIENTS:'Clients'};
function doGet(){return out({ok:true,service:'booking-api'})}
function doPost(e){try{const b=JSON.parse(e.postData.contents||'{}');const u=auth_(b.initData);return out(route_(b,u))}catch(err){return out({ok:false,error:err.message||'Server error'})}}
function route_(b,u){switch(b.action){case'bootstrap':return bootstrap_(u);case'getSlots':return slots_(u,b.date,b.serviceId);case'createBooking':return create_(u,b);case'myBookings':return mine_(u);case'cancelBooking':return cancel_(u,b.bookingId);case'adminCalendar':master_(u);return adminCalendar_(b.date);case'adminAddBlock':master_(u);return addBlock_(b);case'adminManualBooking':master_(u);return manual_(b);default:throw Error('Unknown action')}}
function bootstrap_(u){const s=settings_(),services=rows_(N.SERVICES).filter(x=>yes(x.active)).sort((a,b)=>Number(a.sort||999)-Number(b.sort||999)).map(x=>({id:String(x.id),name:String(x.name),price:Number(x.price||0),duration:Number(x.duration||0),type:String(x.type||'single')}));return{ok:true,user:{id:String(u.id),firstName:u.first_name||'',isMaster:isMaster_(u)},settings:{salonName:s.SALON_NAME||'Booking',logoUrl:s.SALON_LOGO_URL||'',slotStep:Number(s.SLOT_STEP_MINUTES||30),buffer:Number(s.BUFFER_MINUTES||15),cancelBefore:Number(s.CANCEL_BEFORE_MINUTES||90),colors:{primary:s.PRIMARY||'#C98A52',primaryDark:s.PRIMARY_DARK||'#9A6034',primaryLight:s.PRIMARY_LIGHT||'#E7B887',bg:s.BG||'#F8F0E7',bgSoft:s.BG_SOFT||'#EFE0D0',card:s.CARD||'#fff',text:s.TEXT||'#33271F',muted:s.MUTED||'#8B7768',accent:s.ACCENT||'#F3E4D4',border:s.BORDER||'#E4CDB7'}},services}}
function slots_(u,date,sid){if(!date||!sid)throw Error('Date and service are required');const s=settings_(),svc=service_(sid),periods=rows_(N.SCHEDULE).filter(x=>String(x.date)===date&&yes(x.active)),blocks=rows_(N.BLOCKS).filter(x=>String(x.date)===date),bookings=rows_(N.BOOKINGS).filter(x=>String(x.date)===date&&['confirmed','pending'].includes(String(x.status)));const step=Number(s.SLOT_STEP_MINUTES||30),buffer=Number(s.BUFFER_MINUTES||15),d=Number(svc.duration),out=[];periods.forEach(p=>{for(let cur=mm(p.start);cur+d<=mm(p.end);cur+=step){const end=cur+d+buffer;if(past_(date,cur,s.TIMEZONE)||overlap_(cur,end,blocks)||overlapBookings_(cur,end,bookings,buffer))continue;out.push(tm(cur))}});return{ok:true,date,serviceId:sid,slots:[...new Set(out)]}}
function create_(u,b){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const svc=service_(b.serviceId),available=slots_(u,b.date,b.serviceId).slots;if(!available.includes(b.start))throw Error('Цей час уже недоступний.');if(!String(b.clientName||'').trim()||!String(b.phone||'').trim())throw Error("Вкажіть імʼя та телефон.");const st=mm(b.start),now=new Date(),id='BK-'+Utilities.getUuid().slice(0,8).toUpperCase();append_(N.BOOKINGS,[id,String(u.id),String(b.clientName).trim(),String(b.phone).trim(),svc.id,svc.name,b.date,b.start,tm(st+svc.duration),svc.duration,'confirmed',String(b.comment||'').slice(0,500),now,now,'','']);client_(u,b.clientName,b.phone);return{ok:true,booking:{id,date:b.date,start:b.start,end:tm(st+svc.duration),serviceName:svc.name,price:svc.price}}}finally{lock.releaseLock()}}
function mine_(u){return{ok:true,bookings:rows_(N.BOOKINGS).filter(x=>String(x.telegramId)===String(u.id)&&['confirmed','pending'].includes(String(x.status))).map(book)}}
function cancel_(u,id){const a=withRows_(N.BOOKINGS).find(x=>String(x.row.id)===String(id));if(!a)throw Error('Запис не знайдено');if(String(a.row.telegramId)!==String(u.id)&&!isMaster_(u))throw Error('Немає доступу');window_(a.row.date,a.row.start);patch_(N.BOOKINGS,a.n,{status:'cancelled',updatedAt:new Date()});return{ok:true}}
function adminCalendar_(date){return{ok:true,date,bookings:rows_(N.BOOKINGS).filter(x=>String(x.date)===date&&['confirmed','pending'].includes(String(x.status))).map(book),blocks:rows_(N.BLOCKS).filter(x=>String(x.date)===date),schedule:rows_(N.SCHEDULE).filter(x=>String(x.date)===date&&yes(x.active))}}
function addBlock_(b){if(!b.date||!b.start||!b.end||mm(b.start)>=mm(b.end))throw Error('Некоректний час');const id='BL-'+Utilities.getUuid().slice(0,8).toUpperCase();append_(N.BLOCKS,[id,b.date,b.start,b.end,String(b.reason||'Заблоковано'),new Date()]);return{ok:true,id}}
function manual_(b){const lock=LockService.getScriptLock();lock.waitLock(10000);try{const svc=service_(b.serviceId),s=mm(b.start),e=s+svc.duration+Number(settings_().BUFFER_MINUTES||15),blocks=rows_(N.BLOCKS).filter(x=>String(x.date)===String(b.date)),books=rows_(N.BOOKINGS).filter(x=>String(x.date)===String(b.date)&&['confirmed','pending'].includes(String(x.status)));if(overlap_(s,e,blocks)||overlapBookings_(s,e,books,Number(settings_().BUFFER_MINUTES||15)))throw Error('Час уже зайнятий');const id='BK-'+Utilities.getUuid().slice(0,8).toUpperCase();append_(N.BOOKINGS,[id,'',String(b.clientName||'').trim(),String(b.phone||'').trim(),svc.id,svc.name,b.date,b.start,tm(s+svc.duration),svc.duration,'confirmed','',new Date(),new Date(),'','']);return{ok:true,id}}finally{lock.releaseLock()}}
function auth_(raw){if(!raw)throw Error('Missing Telegram initData');const token=PropertiesService.getScriptProperties().getProperty('BOT_TOKEN');if(!token)throw Error('BOT_TOKEN is not configured');const q=raw.split('&').map(x=>x.split('=')),d={};q.forEach(([k,v])=>{d[k]=decodeURIComponent(v||'')});const hash=d.hash;if(!hash)throw Error('Missing hash');const check=Object.keys(d).filter(k=>k!=='hash').sort().map(k=>k+'='+d[k]).join('\n');const key=Utilities.computeHmacSha256Signature('WebAppData',token),dig=Utilities.computeHmacSha256Signature(check,key).map(x=>(x<0?x+256:x).toString(16).padStart(2,'0')).join('');if(dig!==hash)throw Error('Invalid Telegram initData');const age=Date.now()/1000-Number(d.auth_date||0);if(age>86400)throw Error('Expired Telegram initData');return JSON.parse(d.user)}
function master_(u){if(!isMaster_(u))throw Error('Доступ до кабінету майстра заборонений')}function isMaster_(u){return String(settings_().MASTER_TELEGRAM_ID||'')===String(u.id)}
function settings_(){const o={};rows_(N.SETTINGS).forEach(x=>o[x.key]=x.value);return o}
function service_(id){const x=rows_(N.SERVICES).find(x=>String(x.id)===String(id)&&yes(x.active));if(!x)throw Error('Послугу не знайдено');return{id:String(x.id),name:String(x.name),price:Number(x.price||0),duration:Number(x.duration||0),type:String(x.type||'single')}}
function rows_(name){const sh=SpreadsheetApp.getActive().getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v[0];return v.slice(1).map(r=>Object.fromEntries(h.map((k,i)=>[String(k),r[i]])))}
function withRows_(name){const sh=SpreadsheetApp.getActive().getSheetByName(name);if(!sh||sh.getLastRow()<2)return[];const v=sh.getDataRange().getValues(),h=v[0];return v.slice(1).map((r,i)=>({row:Object.fromEntries(h.map((k,j)=>[String(k),r[j]])),n:i+2}))}
function append_(name,row){SpreadsheetApp.getActive().getSheetByName(name).appendRow(row)}function patch_(name,n,p){const sh=SpreadsheetApp.getActive().getSheetByName(name),h=sh.getRange(1,1,1,sh.getLastColumn()).getValues()[0];Object.keys(p).forEach(k=>{const i=h.indexOf(k);if(i>=0)sh.getRange(n,i+1).setValue(p[k])})}
function client_(u,name,phone){const a=withRows_(N.CLIENTS).find(x=>String(x.row.telegramId)===String(u.id)),now=new Date();if(a)patch_(N.CLIENTS,a.n,{name,phone,lastSeen:now,bookingsCount:Number(a.row.bookingsCount||0)+1});else append_(N.CLIENTS,[String(u.id),name,phone,now,now,1])}
function book(x){return{id:String(x.id),clientName:String(x.clientName||''),phone:String(x.phone||''),serviceId:String(x.serviceId||''),serviceName:String(x.serviceName||''),date:String(x.date||''),start:String(x.start||''),end:String(x.end||''),duration:Number(x.duration||0),status:String(x.status||''),comment:String(x.comment||'')}}
function window_(date,start){const s=settings_(),dt=Utilities.parseDate(date+' '+start,s.TIMEZONE||'Europe/Kyiv','yyyy-MM-dd HH:mm'),diff=(dt.getTime()-Date.now())/60000;if(diff<Number(s.CANCEL_BEFORE_MINUTES||90))throw Error('Скасування доступне не пізніше ніж за '+Number(s.CANCEL_BEFORE_MINUTES||90)+' хвилин до запису')}
function overlap_(s,e,rs){return rs.some(r=>s<mm(r.end)&&e>mm(r.start))}function overlapBookings_(s,e,rs,b){return rs.some(r=>s<(mm(r.end)+b)&&e>mm(r.start))}
function past_(date,m,tz){const now=Utilities.formatDate(new Date(),tz||'Europe/Kyiv','yyyy-MM-dd HH:mm');return date+' '+tm(m)<=now}function mm(t){const p=String(t).split(':').map(Number);return p[0]*60+p[1]}function tm(m){return String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')}function yes(v){return v===true||String(v).toLowerCase()==='true'||String(v)==='1'}function out(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON)}

function setupSheets(){const ss=SpreadsheetApp.getActive();const defs={Settings:[['key','value'],['SALON_NAME','Sugar Katerina'],['MASTER_TELEGRAM_ID','PASTE_MASTER_TELEGRAM_ID'],['TIMEZONE','Europe/Kyiv'],['SLOT_STEP_MINUTES','30'],['BUFFER_MINUTES','15'],['CANCEL_BEFORE_MINUTES','90'],['REMINDER_1_HOURS','24'],['REMINDER_2_HOURS','2'],['PRIMARY','#C98A52'],['PRIMARY_DARK','#9A6034'],['PRIMARY_LIGHT','#E7B887'],['BG','#F8F0E7'],['BG_SOFT','#EFE0D0'],['CARD','#FFFFFF'],['TEXT','#33271F'],['MUTED','#8B7768'],['ACCENT','#F3E4D4'],['BORDER','#E4CDB7'],['SALON_LOGO_URL',''],['WEB_APP_URL',''],['DEV_MODE','false']],Services:[['id','name','price','duration','type','active','sort'],['deep_bikini','Глибоке бікіні',250,30,'single',true,1],['classic_bikini','Класичне бікіні',200,20,'single',true,2],['arms_elbow','Ручки до ліктя',100,20,'single',true,3],['arms_full','Ручки повністю',150,30,'single',true,4],['underarms','Пахви',100,10,'single',true,5],['upper_lip','Вусики',100,10,'single',true,6],['legs_knees','Ніжки до колін',200,30,'single',true,7],['legs_full','Ніжки повністю',250,40,'single',true,8],['buttocks','Сідниці',100,10,'single',true,9],['lower_back','Поясниця',100,10,'single',true,10],['belly_strip','Живіт доріжка',100,10,'single',true,11],['belly_full','Живіт повністю',100,10,'single',true,12],['alginate_mask','Альгінатна маска',100,15,'single',true,13],['ingrown_hair','Механічна чистка врослого волосся',100,30,'single',true,14],['complex_1','Бікіні класичне + пахви + ніжки до колін',400,60,'complex',true,20],['complex_2','Бікіні глибоке + пахви + ручки повністю',550,80,'complex',true,21],['complex_3','Бікіні глибоке + ніжки до колін + пахви',600,80,'complex',true,22],['complex_4','Бікіні глибоке + ніжки повністю + пахви',650,90,'complex',true,23]],Schedule:[['date','start','end','active']],Blocks:[['id','date','start','end','reason','createdAt']],Bookings:[['id','telegramId','clientName','phone','serviceId','serviceName','date','start','end','duration','status','comment','createdAt','updatedAt','reminder24Sent','reminder2Sent']],Clients:[['telegramId','name','phone','firstSeen','lastSeen','bookingsCount']]};Object.keys(defs).forEach(n=>{let sh=ss.getSheetByName(n);if(!sh)sh=ss.insertSheet(n);sh.clear();const d=defs[n];sh.getRange(1,1,d.length,d[0].length).setValues(d);sh.setFrozenRows(1);sh.getRange(1,1,1,d[0].length).setFontWeight('bold')});ss.setSpreadsheetTimeZone('Europe/Kyiv')}
function setTelegramMenuButton(){const token=PropertiesService.getScriptProperties().getProperty('BOT_TOKEN'),url=settings_().WEB_APP_URL;if(!token||!url)throw Error('Set BOT_TOKEN and WEB_APP_URL first');UrlFetchApp.fetch('https://api.telegram.org/bot'+token+'/setChatMenuButton',{method:'post',contentType:'application/json',payload:JSON.stringify({menu_button:{type:'web_app',text:'📅 Записатися',web_app:{url}}})})}
function sendBookingReminders(){const s=settings_(),token=PropertiesService.getScriptProperties().getProperty('BOT_TOKEN');if(!token)return;withRows_(N.BOOKINGS).forEach(a=>{const b=a.row;if(!b.telegramId||String(b.status)!=='confirmed')return;const dt=Utilities.parseDate(String(b.date)+' '+String(b.start),s.TIMEZONE||'Europe/Kyiv','yyyy-MM-dd HH:mm'),h=(dt-Date.now())/3600000;if(!b.reminder24Sent&&h<=Number(s.REMINDER_1_HOURS||24)&&h>0){sendT_(token,b.telegramId,`🔔 Нагадування про запис\n\n${b.serviceName}\n📅 ${b.date}\n🕐 ${b.start}`);patch_(N.BOOKINGS,a.n,{reminder24Sent:new Date()})}if(!b.reminder2Sent&&h<=Number(s.REMINDER_2_HOURS||2)&&h>0){sendT_(token,b.telegramId,`🔔 Нагадування: сьогодні у Вас запис\n\n${b.serviceName}\n🕐 ${b.start}`);patch_(N.BOOKINGS,a.n,{reminder2Sent:new Date()})}})}
function sendT_(token,chat,text){UrlFetchApp.fetch('https://api.telegram.org/bot'+token+'/sendMessage',{method:'post',contentType:'application/json',payload:JSON.stringify({chat_id:chat,text})})}
function setupReminderTrigger(){ScriptApp.getProjectTriggers().filter(t=>t.getHandlerFunction()==='sendBookingReminders').forEach(t=>ScriptApp.deleteTrigger(t));ScriptApp.newTrigger('sendBookingReminders').timeBased().everyMinutes(5).create()}
